Comparison Api
tournesol-app/tournesol-backend pull request #16
Opened 2021-07-03 14:43 UTC by elineda

Api from get / post comparison

/comparison/ -> get, all yours comparison
/comparison/ -> post, create or update a comparison (same route need send all object)
/comparison/get_comparison/ -> get, one comparison with video_1 and video_2 (video_id)
/comparison/liste_comparison/ -> get, list of comparison with search parameter

2021-07-03 22:26 UTC, sergia-ch commented
@elineda maybe add video IDs (first and second) to the update URL? It would make it more human readable and aesthetically pleasing 😍

`/comparison/ -> post, create or update a comparison (same route need send all object)`

So maybe we have `/comparison/AwesomeVideo1/AwesomeVideo2/` for item 2 in the list above🧘‍♀️

2021-07-04 15:53 UTC, lfaucon requested changes

2021-07-04 15:53 UTC, lfaucon commented on tournesol/serializers.py
> +        exclude = []
Looks like this class misses the formatiing for the field video_1 and video_2 (see example below with first inverted query, then normal query). The fix should also be such that video_2 (in response to user query) contains the id of the video_1 (in db) and inversely, isn't it?

```
curl -H "Authorization: Bearer <token>" 'http://127.0.0.1:8000/comparison/get_comparison/?video_1=Os3Twlkc8_4&video_2=KWZvPb9XKVs' -X GET

{
    "id":7868,
    "criteria_scores":[
        {"score":-50.0,"criteria":"largely_recommended","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"reliability","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"importance","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"engaging","weight":1.0,"comparison":7868},
        {"score":-75.0,"criteria":"pedagogy","weight":1.0,"comparison":7868},
        {"score":-75.0,"criteria":"layman_friendly","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"diversity_inclusion","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"backfire_risk","weight":1.0,"comparison":7868},
        {"score":-50.0,"criteria":"better_habits","weight":1.0,"comparison":7868},
        {"score":-76.0,"criteria":"entertaining_relaxing","weight":1.0,"comparison":7868}
    ],
    "duration_ms":30937.0,
    "datetime_lastedit":"2021-07-04T14:49:50.943183Z",
    "datetime_add":"2021-05-25T18:14:59.560567Z",
    "video_1_2_ids_sorted":"6784_7109",
    "user":6897,
    "video_1":6784,
    "video_2":7109
}


curl -H "Authorization: Bearer <token>" 'http://127.0.0.1:8000/comparison/get_comparison/?video_2=Os3Twlkc8_4&video_1=KWZvPb9XKVs' -X GET

{
    "criteria_scores":[
        {"criteria":"largely_recommended","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"reliability","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"importance","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"engaging","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"pedagogy","score":75.0,"weight":1.0,"comparison":7868},
        {"criteria":"layman_friendly","score":75.0,"weight":1.0,"comparison":7868},
        {"criteria":"diversity_inclusion","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"backfire_risk","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"better_habits","score":50.0,"weight":1.0,"comparison":7868},
        {"criteria":"entertaining_relaxing","score":76.0,"weight":1.0,"comparison":7868}
    ],
    "video_1":{"video_id":"KWZvPb9XKVs"},
    "video_2":{"video_id":"Os3Twlkc8_4"},
    "duration_ms":30937.0,
    "datetime_lastedit":"2021-07-04T14:49:50.943183Z",
    "datetime_add":"2021-05-25T18:14:59.560567Z",
    "user":6897
}
```

2021-07-04 15:53 UTC, lfaucon commented on tournesol/views/comparison.py
> +        comparisons = Comparison.objects.all()[offset:limit] if not video \
Right now this exposes all comparisons from all users. We do not plan to make all the comparisos public yet (although we want to add later the field `is_public` on the Comparison model and expose all comparisons that contributors choose to make public)

Could fix here for now simply by adding `user=request.user` or using `self.get_queryset`

2021-07-04 19:06 UTC, lfaucon commented
Thanks a lot for this contribution @elineda !

2021-07-04 19:38 UTC, elineda commented on tournesol/views/comparison.py
> +        video_1 = get_object_or_404(Video, video_id=video_1_id)
For me it's better to add video route for create it. It's bad idea to do everything in same route.
I suppose also in front it will be a different form.

2021-07-04 19:43 UTC, elineda commented on tournesol/urls.py
> +app_name = 'comparison'
it's the namespace of the url, you use it in template or reverse, redirect function 
https://docs.djangoproject.com/en/3.2/topics/http/urls/

2021-07-04 19:45 UTC, elineda commented on tournesol/serializers.py
> +        exclude = []
Symply forgot the inversed one.
I choose to not use the pk because it's far more difficult to fin a youtube id than a pk. In case of attack it's safer

2021-07-04 19:56 UTC, elineda commented
> 
> 
> @elineda maybe add video IDs (first and second) to the update URL? It would make it more human readable and aesthetically pleasing 😍
> 
> `/comparison/ -> post, create or update a comparison (same route need send all object)`
> 
> So maybe we have `/comparison/AwesomeVideo1/AwesomeVideo2/` for item 2 in the list above🧘‍♀️

2 thing against it : 
- first of all, for put that in place we need to change a lot of thing and don't use restframework system as we will need to change url pattern that's a bad idea for maintainability.
- second my way of thinking about this api it's we send an object. The video_id is a part of this object, I don't see a point to separate it from the json object for put this on a url. Also a parameter on a url is for identify an object (1/, 2/ a pk) but here (video1/video2/ and video2/video1/) is the same object but not the same url.

2021-07-05 19:17 UTC, lfaucon commented on tournesol/views/comparison.py
> +        video_1 = get_object_or_404(Video, video_id=video_1_id)
Do you recommend that the frontend does a first one api call to create both videos, then a second one to add the comparison?

2021-07-05 19:19 UTC, lfaucon commented on tournesol/serializers.py
> +        exclude = []
Yes, and it is much more actionable for the frontend to receive youtube Ids :)

2021-07-05 19:21 UTC, elineda commented on tournesol/views/comparison.py
> +        video_1 = get_object_or_404(Video, video_id=video_1_id)
yep

2021-07-07 15:53 UTC, lfaucon commented
😃 Thanks a lot!

2021-07-07 15:54 UTC, lfaucon approved these changes

2021-07-07 15:55 UTC, merged