Ml train work
tournesol-app/tournesol-backend pull request #24
Opened 2021-07-22 16:39 UTC by OscarVlld

- Move files unused in production to /dev
- Create some tests
- Increase training speed
- Add early stopping
- Allow gpu training

2021-07-27 19:56 UTC, sergia-ch commented on ml/data_utility.py
> +        return full.cuda()
(opinion) The way I do this (to replace "if gpu" in tons of places) in my torch projects is to create a variable "device" that is created somewhere at the beginning of the script, and then all functions just have a "device" argument and they do "tensor.to(device)" where needed -- imho it's less cumbersome this way and scales well to multi-gpu setups https://github.com/sergia-ch/causality-disentanglement-rl/blob/master/sparse_causal_model_learner_rl/learners/abstract_learner.py#L35

2021-07-27 19:58 UTC, sergia-ch commented on ml/dev/ml_benchmark.py
> +    _ = hfbbt(TT, RR)
maybe a bit too cryptic :)
-- FBBT?
-- HFBBT! TT, RR...

:)

2021-07-27 20:00 UTC, sergia-ch commented on ml/dev/ml_tests.py
> +def test_rescale_rating():
maybe would be nice to 1-line descriptions of what tests do, as it's hard to get what went wrong when they fail (I myself don't always do that..)

2021-07-27 20:02 UTC, sergia-ch commented on ml/hyperparameters.py
>      """ defaults training parameters """
In the previous version of Tournesol I used gin-config -- it eliminates this kind of dictionaries altogether and moves all the configuration into separate .gin files with some python support inside. But it's an aesthetical choice, not an objective one :) https://github.com/google/gin-config

2021-07-28 08:16 UTC, OscarVlld commented on ml/dev/ml_tests.py
> +def test_rescale_rating():
For now  "test_foo()" is really just testing the "foo()" function (there are 2-3 exceptions but I think there is a 1-line description for them). Do you think more description is needed ?

2021-07-28 08:18 UTC, OscarVlld commented on ml/hyperparameters.py
>      """ defaults training parameters """
Thanks, I'll look into this.

2021-07-28 08:24 UTC, OscarVlld commented on ml/dev/ml_benchmark.py
> +    _ = hfbbt(TT, RR)
I'll see what I can do :)

2021-07-28 08:28 UTC, OscarVlld commented on ml/data_utility.py
> +        return full.cuda()
Good idea, thanks

2021-07-29 13:18 UTC, OscarVlld commented on ml/hyperparameters.py
>      """ defaults training parameters """
I've moved parameters to "hyperparameters.gin".

2021-07-29 13:18 UTC, OscarVlld commented on ml/dev/ml_benchmark.py
> +    _ = hfbbt(TT, RR)
It should be a bit clearer now.

2021-07-29 13:22 UTC, OscarVlld commented on ml/data_utility.py
> +        return full.cuda()
Done, but i can't really test gpu mode as I don't have one. I'd be happy if anyone could just tell me if it runs :)

2021-07-29 17:05 UTC, lfaucon reviewed
First of all thanks for your work. Adding tests, cleaning up the structure of the code and improving the performance are all really great.

A few comments to help you better contribute to the project:
- When starting to work on something new, go back to the main branch, pull the latest version, then create a branch with your changes. Right now your PR has a very long list of commits because it includes everything from your previous branch.
- The PR description is very helpful for understanding and reviewing your changes. If each of these 5 points could be separated (I believe they can), then it would be easiest for reviewing and merging code to do these on separate branches and using separate Pull Request. A problem you may have when submitting changes 1, 2, 3, 4 & 5 is that if the reviewer disagrees with 5, then it blocks updating the code with 1, 2, 3, & 4. 
- This PR modifies 1900 lines of code. It makes it very difficult to review in details. Best changes are the ones that take less than 100 lines (100 good lines of code are complicated enough). Also you add a lot of lines, a lot of them are doctoring comments which is great, but a lot of them are part of the model. The larger the codebase gets the harder it is to work on it. The best changes improve the software and have less lines of code :)

2021-07-29 17:12 UTC, lfaucon requested changes
There was a problem with installing requirements before test, which I fixed. It now looks like your test is failing. Looking at the output of the algorithm when I run the new version it indeed seems incorect. On my side values are all too cléose to 0. We can call about this if you want

2021-07-29 20:31 UTC, OscarVlld commented on ml/dev/fake_data.py
> +import scipy.stats as st
I use it because I use a custom density function. I am not sure numpy can do this but I can search a bit more.

2021-07-30 08:22 UTC, OscarVlld commented on ml/management/commands/ml_train.py
> +from ml.dev.experiments import run_experiment
The import is now conditioned by TOURNESOL_DEV environment variable.

2021-07-30 08:22 UTC, OscarVlld commented on ml/ml_requirements.txt
> +pytest==6.2.4
Removed.

2021-07-30 08:22 UTC, OscarVlld commented on ml/management/commands/ml_train.py
> +from ml.core import ml_run
Done.

2021-07-30 08:23 UTC, OscarVlld commented on ml/management/commands/ml_train.py
> +from tournesol.models.video import VideoCriteriaScore
I think it's ok now.

2021-07-31 09:40 UTC, lfaucon commented on ml/dev/fake_data.py
> +import scipy.stats as st
Ok!

2021-07-31 09:46 UTC, lfaucon requested changes
I'm happy merging these changes. Thanks for the work.

I may only ask you to move the files containing tests in a folder `/ml/tests/` which is already ignored by bandit

See here for info: https://stackoverflow.com/questions/63829128/how-can-i-make-bandit-skip-b101-within-tests 

And the file `bandit.yml`

2021-07-31 10:41 UTC, OscarVlld commented
As far as I can see flake8 and pylint failures don't come from files I edited so we may be good to go.

2021-08-01 11:36 UTC, lfaucon commented
Thanks @OscarVlld

2021-08-01 11:37 UTC, merged