Ml separate dev
tournesol-app/tournesol-backend pull request #32
Opened 2021-08-02 15:33 UTC by OscarVlld

2021-08-02 15:42 UTC, OscarVlld commented on pytest.ini
> +    ignore::django.utils.deprecation.RemovedInDjango41Warning
Same as my other PR, I don't know if we want this on main.

2021-08-03 16:33 UTC, lfaucon commented on pytest.ini
> +    ignore::django.utils.deprecation.RemovedInDjango41Warning
Yes, we will update this on main because we can't do anything about this warning.

2021-08-03 17:13 UTC, lfaucon requested changes

2021-08-03 17:13 UTC, lfaucon commented on ml/dev/licchavi_dev.py
> +        super()._update_hist(epoch, fit, s, gen, reg)
👍

2021-08-03 17:13 UTC, lfaucon commented on ml/management/commands/ml_train_dev.py
> +Machine Learning main python file
Probably better to not call it "main python file", but "python file for development"

2021-08-03 17:13 UTC, lfaucon commented
Nice refactor!

2021-08-04 09:53 UTC, OscarVlld commented on ml/management/commands/ml_train_dev.py
> +Machine Learning main python file
Yes, thanks. I forgot to change it after copy-pasting ml_train.

2021-08-04 10:04 UTC, OscarVlld commented on ml/dev/licchavi_dev.py
> +        self.test_mode = test_mode
It is actually like this:
- Licchavi -> test_mode == False  (so I removed it altogether)
- LicchaviDev -> test_mode == True or False  (so I kept it)

Indeed, self.test_mode is boolean for the usage of artificially generated data (providing ground truths). This type of data is never used in production, but not always for developpement (I sometimes use real data or manual comparisons as input). As I plan to use only LicchaviDev for tests, it must be able to adapt to those different situations.

2021-08-04 15:41 UTC, lfaucon commented on ml/dev/licchavi_dev.py
> +        self.test_mode = test_mode
Understood! Thanks for clarifying

2021-08-06 15:54 UTC, merged