Sandre/api video creation
tournesol-app/tournesol-backend pull request #33
Opened 2021-08-06 12:55 UTC by sandre35

2021-08-06 17:32 UTC, elineda requested changes

2021-08-06 17:32 UTC, elineda commented on tournesol/serializers.py
> +        fields = "__all__"
c'est sur que l'on met tout ?

2021-08-06 17:32 UTC, elineda commented on tournesol/views/video.py
> +        except Video.DoesNotExist:
don't raise postgres error. do get object or 404

2021-08-06 17:32 UTC, elineda commented on tournesol/views/video.py
> +            criteria_dict[criteria.criteria] = VideoCriteriaScoreSerializer(criteria)
this should be on serialiser no there

2021-08-06 17:32 UTC, elineda commented on tournesol/views/video.py
> +            serializer.save()
where do you save VideoCriteriaScore ?

2021-08-06 17:34 UTC, elineda requested changes

2021-08-06 17:34 UTC, elineda commented on tournesol/views/video.py
> +class VideoList(APIView):
why no use modelviewset ?

2021-08-06 18:03 UTC, lfaucon commented on tournesol/views/video.py
> +            serializer.save()
VideoCriteriaScores are set by the ML algorithm on the backend. This API endpoint should not edit them

2021-08-06 19:17 UTC, sandre35 commented on tournesol/views/video.py
> +class VideoList(APIView):
@elineda This is what is recommended in the documentation : https://www.django-rest-framework.org/tutorial/3-class-based-views/

2021-08-06 19:22 UTC, sandre35 commented on tournesol/views/video.py
> +            serializer.save()
What is saved is the Video, not the VideoCriteriaScore. I call the VideoSerializer, not VideoCriteriaScoreSerializer

2021-08-06 19:33 UTC, elineda commented on tournesol/views/video.py
> +class VideoList(APIView):
yeah but no... part 4 of tutorial 👍 https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/
look what they use as class

2021-08-08 06:44 UTC, lfaucon requested changes

2021-08-08 06:44 UTC, lfaucon commented on tournesol/tests/test.video.py
> +from django.test import TestCase
the file `test.video.py` is not selected by pytest when running tests (neither on the ci, neither when running `pytest tournesol` locally). Fixing the name to `test_video.py` of `test_api_video.py` works well with pytest. 

However the tests fail currently.

Additionally I'd recommend adding a test with incorrect video ids. And adding two tests for the behavior when fetching an existing or non-existing video

2021-08-08 06:57 UTC, lfaucon commented on tournesol/urls.py
> +        "videos/<str:youtube_video_id>",
I'm not sure about this, but I recall some confusing behaviour with or without a `/` at the end of the url path. Could you check what is recommended for this and either modify the `videos` path or the two above?

2021-08-08 07:04 UTC, lfaucon commented on tournesol/serializers.py
> +    videocriterias = VideoCriteriaScoreSerializer(many=True, required=False)
I'd recommend renaming this attribute `criterias` for simplicity

2021-08-10 19:37 UTC, lfaucon approved these changes

2021-08-10 21:06 UTC, merged