API endpoint for video recommendations
tournesol-app/tournesol-backend pull request #36
Opened 2021-08-13 17:00 UTC by elineda

Endpoint /videos, GET request returns sorted list of videos using parameters:

limit: default 10
offset: default 0
date_lte, date_gte
language
<CRITERIA_NAME_WEIGHT> value between 0 and 100 (default: 50) the weight of this criteria in the ranking
The video must be sorted based of the sum of scores per criteria multiplied by their weights <CRITERIA_NAME_WEIGHT>

The returned video must contain most of the data about the video (most fields available on the Video and VideoCriteriaScores model)

Add search parameter for a text search using title / metadata of the videos. Discuss with @lfaucon and @lenhoanglnh if you want to implement this feature

2021-08-18 19:26 UTC, sandre35 requested changes
Good job on the implementation !

2021-08-18 19:26 UTC, sandre35 commented on settings/settings.py
> +
Is it necessary to keep blank space?

2021-08-18 19:26 UTC, sandre35 commented on tests/test_api_video_crud_manipulation.py
> +        self.assertEquals(response.status_code, status.HTTP_201_CREATED)
Why is the status of 201 ? Nothing is created on the back ?

2021-08-18 19:26 UTC, sandre35 commented on tournesol/views/video.py
> +                                                       request.query_params.get('offset').isdigit() else 0
the code is not that easy to read with multiple conditions. Could you decompose the code like that so that is more visual?
```
if multiple_condition :
   do...
```

2021-08-18 19:26 UTC, sandre35 commented on tournesol/views/video.py
> +                pass
Why do need try/ except ?
Precise the error that can be raised after except in that case

2021-08-18 19:26 UTC, sandre35 commented on tournesol/views/video.py
> +                pass
same as date_lte

2021-08-20 14:44 UTC, GresilleSiffle commented on tests/test_api_video_crud_manipulation.py
> +    response = client.get('localhost:8000/video/')
Shouldn't the API calls be made in each test method instead?

A response being specific to a request, I'll move both `client` and `response` to the relevent methods.

2021-08-20 14:50 UTC, GresilleSiffle commented on tests/test_api_video_crud_manipulation.py
> +class VideoApi(TestCase):
The `VideoViewSet` has three methods:
- `create`
- `retrieve`
- `list`

Maybe we can increase the coverage of this test case by adding at least one test for:
- each successful response of each endpoint
- each premature response like BAD_REQUEST or NOT_FOUND of each endpoint

2021-08-20 14:54 UTC, GresilleSiffle commented on tests/test_api_video_crud_manipulation.py
> +        - permission checks
The current test doesn't seem to checks neither authorizations nor permissions.

I'd recommand removing those indications if the tests are not updated, as they can mislead the reader.

2021-08-21 10:17 UTC, elineda commented on tournesol/views/video.py
> +                                                       request.query_params.get('offset').isdigit() else 0
If we do one action or just assign variable I usually use one line, and there is only two condition :D

2021-08-21 10:17 UTC, elineda commented on tournesol/views/video.py
> +                pass
a wrong date can return an error with strptime

2021-08-23 16:10 UTC, GresilleSiffle commented on tournesol/views/video.py
>          return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
The DRF `ModelViewSet` inherit from the `mixin.CreateModelMixin` and thus provide a `create` method that takes care of everything for us.

We should use it a lot. It allows us to focus on complex code while leaving the responsability of this kind of chose to the framework. By re-writing the rendering logic, we are also re-writing part of DRF which is rarely a good idea. 

see: https://github.com/encode/django-rest-framework/blob/master/rest_framework/mixins.py#L12

Also the [DRF tutorial](https://www.django-rest-framework.org/tutorial/1-serialization/) is extremely good and teach how to take full advantage of the `mixins`. I've learned a lot : )

2021-08-25 07:40 UTC, elineda commented
I deleted tests/test_api_video_crud_manipulation.py it was a creation of Sabamine and no longer need as video test already implemented.

2021-08-27 14:34 UTC, sandre35 submitted a review, later dismissed

2021-08-30 17:26 UTC, lfaucon requested changes
Hi @elineda 

Sorry for taking so long with the review. I know it isn't fun to get back to an old Pull Request.

2021-08-30 17:26 UTC, lfaucon commented on tournesol/views/video.py
> +            for score in VideoCriteriaScore.objects.filter(video=video):
This will lead to 1 database request per video, isn't it? I think it would be preferrable to rewrite it like this: 

```Python
      for video in queryset.prefetch_related("criteria_scores"):
            total = 0
            for criteria_score in video.criteria_scores.all():
                score_query_weight = 50
                if request.query_params.get(score.criteria) \
                        and request.query_params.get(score.criteria).isdigit():
                    score_query_weight = request.query_params.get(score.criteria)
                total += criteria_score.score * score_query_weight
            video.total = total
            data.append(video)
```

I also modified a little bit the condition to use 50 as the default weight.

2021-08-30 18:13 UTC, elineda commented on tournesol/views/video.py
> +            for score in VideoCriteriaScore.objects.filter(video=video):
ok

2021-08-31 16:51 UTC, lfaucon submitted a review, later dismissed

2021-08-31 17:04 UTC, amatissart commented on tournesol/views/video.py
> +        data = data[offset:limit]
Using `data = data[offset: offset+limit]` would be consistent with the [`LimitOffsetPagination`](https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination), already used by the `VideoRateLaterList`.

2021-08-31 19:25 UTC, GresilleSiffle commented on tournesol/views/video.py
> +        return Response('forbidden', status=status.HTTP_403_FORBIDDEN)
In this case the HTTP status 501 would be more appropriate. It's not that important, but it' sgood to konw : )

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

```python
return Response('forbidden', status=status.HTTP_501_NOT_IMPLEMENTED)
```

2021-08-31 19:37 UTC, lfaucon commented on tournesol/views/video.py
> +        data = data[offset:limit]
Agreed!

2021-08-31 19:40 UTC, elineda commented on tournesol/views/video.py
> +        data = data[offset:limit]
so we need to change some code, as we need do offset after score calculation.

2021-08-31 19:53 UTC, GresilleSiffle commented on tournesol/views/video.py
> +        data = data[offset:limit]
I wasn't aware of that, indeed. It's better to fix the error by cheking the limit and offset value then.

2021-08-31 19:53 UTC, lfaucon commented on tournesol/views/video.py
> +        return Response('forbidden', status=status.HTTP_403_FORBIDDEN)
Maybe 404 is better than 403 otherwise the API client might try to authenticate so that the request is not forbidden anymore?

2021-08-31 19:59 UTC, elineda commented on tournesol/views/video.py
> +        return Response('forbidden', status=status.HTTP_403_FORBIDDEN)
404 is no found :> 405 is nice for me

2021-08-31 20:09 UTC, lfaucon commented on tournesol/views/video.py
> +        return Response('METHOD_NOT_ALLOWED', status=status.HTTP_405_METHOD_NOT_ALLOWED)
:+1:

2021-08-31 20:38 UTC, lfaucon approved these changes

2021-08-31 20:39 UTC, merged