Bind api youtube to collect data
tournesol-app/tournesol-backend pull request #38
Opened 2021-08-14 21:26 UTC by sandre35

2021-08-19 10:09 UTC, sandre35 commented
@jstainer-kleis I try to run de script `run-docker-compose.sh` at this stage of commits, but the following command does not works:
"docker exec --env PGPASSWORD=password dev-env_db_1 bash -c "psql -1 -q -d tournesol -U user < /var/lib/postgresql/data/dump.sql"
In the console many messages like this are printed : "ERROR:  current transaction is aborted, commands ignored until end of transaction block'
Do you know which change(s) caused this issue?

2021-08-22 08:08 UTC, lfaucon requested changes
Thanks for looking into the YoutubeAPI and setting it up! Really great work :100:

2021-08-22 08:08 UTC, lfaucon commented on tournesol/views/video.py
> +        yt_info = api_youtube(request.data["video_id"])["items"][0]
This should not happen here. 
It should happen when creating a video, then be stored in our database. 
The VideoViewSet should then fetch theses fields from the model.

Otherwise we would trigger a Youtube API call for every video fetch which will quickly be more than 10k/day.

Later, we will implement a sort of queue to update video information (title changes, number of views and like, ...). But this is low priority right now.

2021-08-22 08:14 UTC, sandre35 commented on tournesol/views/video.py
> +        yt_info = api_youtube(request.data["video_id"])["items"][0]
Actually, the call of the API is done when creating a video ( in the function create), not in the retrieve function that get the video corresponding the the id given in parameter

2021-08-22 08:18 UTC, lfaucon commented
Please, take care of fixing pytest

1. Should we have one Youtube API key on CircleCI to run test?
2. Should we mock the api call within tests?

2021-08-23 18:50 UTC, jstainer-kleis commented on tournesol/middleware.py
> +    # os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
I'd completely remove that to avoid a mishap and use an env variable for development.

2021-08-23 18:57 UTC, jstainer-kleis commented
lgtm
pending question: how do we proceed for Google accounts / API keys creation and management?

2021-08-23 20:14 UTC, lfaucon commented on tournesol/views/video.py
> +        yt_info = api_youtube(request.data["video_id"])["items"][0]
Correct! I think some part of the code was hidden in the diff I looked at and I wrongly thought this part of the code was part of `retrieve`. Please ignore my comment!

2021-08-23 20:15 UTC, lfaucon approved these changes

2021-08-23 20:18 UTC, lfaucon commented
@jstainer-kleis Probably:
- 1 secret production API key with the tournesol.application@gmail.com account (let's set it up together later)
- each dev sets his/her personal API key for local dev if needed
- 1 not so secret  API key with ??? account for staging

2021-08-23 20:26 UTC, sandre35 commented on tournesol/middleware.py
> +    # os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
@jstainer-kleis so you want to remove the comments on line 14 to 16 ?

2021-08-24 18:47 UTC, lfaucon commented on tournesol/middleware.py
> +    # os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"
@jstainer-kleis I'd recommend keeping it here because it helps development. The risk of mistakenly uncommenting this part is low

2021-08-24 20:43 UTC, lfaucon requested changes

2021-08-24 20:43 UTC, lfaucon commented on README.md
> +* Setup you credentials by getting a API key and creating a ID client OAuth 2.0
Are you sure about using the "OAuth 2. Client ID". It seems that a simple API key would be easier to use?

2021-08-24 20:43 UTC, lfaucon commented on tournesol/views/video.py
> +            yt_info = api_youtube(request.data["video_id"])["items"][0]
Would be nice if this happened asynchronously. The client request to create the video returns immediatly, while the process that fetches the metadata continues in the background

2021-08-24 21:18 UTC, lfaucon commented on tournesol/views/video.py
> +            yt_info = api_youtube(request.data["video_id"])["items"][0]
That would be premature optimization. Resolving

2021-08-24 21:19 UTC, lfaucon commented on tournesol/views/video.py
> +            }
We should not have a call to Youtube API if the video is already in our db and we have already fetched the metadata

2021-08-25 08:01 UTC, elineda requested changes

2021-08-25 08:01 UTC, elineda commented on tournesol/views/video.py
> +        try:
why we do that on retrieve on no on create ?

2021-08-25 08:32 UTC, sandre35 commented on tournesol/views/video.py
> +        try:
It's the same remak as Louis ^^. It is on the create function not on the retrieve one

2021-08-25 08:33 UTC, sandre35 commented on tournesol/middleware.py
> +    return (response)
I mean it is not really a part of the application itself. It just a call to another api. Where would you place it?

2021-08-25 08:44 UTC, elineda commented on tournesol/middleware.py
> +    return (response)
a utils folder for example.

2021-08-28 07:14 UTC, lfaucon approved these changes

2021-08-28 07:25 UTC, lfaucon commented
Thanks all for testing, reviewing and discussing this. It's an important piece of Tournesol's backend.

Let's dicsuss possible abuse of this endpoint in a separate thread. I created a ticket for it: https://github.com/tournesol-app/tournesol-meta/issues/99

2021-08-28 07:26 UTC, merged