Registration mails password management
tournesol-app/tournesol-backend pull request #40
Opened 2021-08-19 06:43 UTC by jstainer-kleis

addresses
[(https://github.com/tournesol-app/tournesol-meta/issues/79)]
and
[https://github.com/tournesol-app/tournesol-meta/issues/80]

2021-08-19 20:08 UTC, lfaucon commented on requirements.txt
> +wrapt==1.12.1
I don't understand why we need to add these 30 new requirements. Can you maybe add a batch-subsection in the documentation file explaining what they are added for? Just so that someone like Elineda does not come in a few weeks to complain that our requirments are getting too large for no reason

2021-08-21 20:25 UTC, jstainer-kleis commented on requirements.txt
> +wrapt==1.12.1
Mistake with pip freeze, sorry. Should be better now.

2021-08-22 07:26 UTC, lfaucon commented on dev-env/run-db-and-local-django.sh
> +docker exec --env PGPASSWORD=password dev-env_db_1 bash -c "psql -d tournesol -U user <<< \"insert into oauth2_provider_application (client_id, redirect_uris, client_type, authorization_grant_type, c
Should this be included in `run-docker-compose.sh` too? 
To avoid code-duplication a `prepare-db.sh` would be good? 
Even better if it can also be used on the local db.

2021-08-22 08:00 UTC, lfaucon requested changes
Once an email is verified through the link used here, how does the Django application know that the email was verified? 

When testing this and looking through the api docs + admin interfacec, I could not find that we store this information. It is needed for us, because we want to only take into consideration verified users when training Tournesol's scores.

2021-08-22 08:18 UTC, jstainer-kleis commented
> Once an email is verified through the link used here, how does the Django application know that the email was verified?
> 
> When testing this and looking through the api docs + admin interfacec, I could not find that we store this information. It is needed for us, because we want to only take into consideration verified users when training Tournesol's scores.

The is_active field should be false until the email is validated.
For email change, it shouldn't be accepted until validation.

2021-08-22 08:20 UTC, lfaucon commented
<img width="535" alt="Screenshot 2021-08-22 at 10 19 36" src="https://user-images.githubusercontent.com/8818081/130347625-0f94c33a-fa1e-488a-85cf-af55ce4c7df4.png">

This field? weird, it doesn't sound at all like it is used for email verification.

2021-08-22 08:22 UTC, jstainer-kleis commented
> <img alt="Screenshot 2021-08-22 at 10 19 36" width="535" src="https://user-images.githubusercontent.com/8818081/130347625-0f94c33a-fa1e-488a-85cf-af55ce4c7df4.png">
> 
> This field? weird, it doesn't sound at all like it is used for email verification.

The user is not considered as fully created until she validates her email.
You can control the field that is used as validation flag with that:
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/user.html#user-verification-flag-field

2021-08-22 08:42 UTC, lfaucon approved these changes

2021-08-22 08:42 UTC, merged